import os
import pathlib
import sys

# ==============================================================================
# КОНФИГУРАЦИЯ
# ==============================================================================
# Имя файла, из которого мы извлекаем константу (ваша рабочая копия)
SOURCE_FILE_NAME = "INIT.SDL" 
# Путь, куда будет сохранен файл констант.
# Предполагаем, что он находится в src/sdal_builder/
TARGET_FILE_PATH = pathlib.Path("src") / "sdal_builder" / "init_constants.py"
# Маркер, который предшествует динамическому списку файлов (Benelux1.SDL)
SPLIT_MARKER_START = b"BENELUX1.SDL"
# ==============================================================================

def extract_and_create_constant():
    """
    Читает INIT.SDL, извлекает статический заголовок и записывает его в
    init_constants.py в формате Python bytes-константы.
    """
    # 1. Проверка наличия исходного файла
    if not pathlib.Path(SOURCE_FILE_NAME).exists():
        print(f"❌ Ошибка: Исходный файл '{SOURCE_FILE_NAME}' не найден.")
        print("Убедитесь, что вы запустили скрипт в папке с рабочим INIT.SDL.")
        sys.exit(1)

    print(f"[ИНФО] Чтение исходного файла: {SOURCE_FILE_NAME}")

    try:
        with open(SOURCE_FILE_NAME, "rb") as f:
            full_content = f.read()

        # 2. Поиск точки разделения
        dynamic_list_start_pos = full_content.find(SPLIT_MARKER_START)

        if dynamic_list_start_pos == -1:
            print(f"❌ Ошибка: Не удалось найти маркер '{SPLIT_MARKER_START.decode()}' в {SOURCE_FILE_NAME}.")
            print("Возможно, вы используете файл, не предназначенный для OEM-сборки.")
            sys.exit(1)
            
        # 3. Извлечение статического блока
        static_header_bytes = full_content[:dynamic_list_start_pos]
        
        # 4. Форматирование для записи в Python-файл
        # repr() преобразует байты в безопасную строку b'...'
        constant_value = f"OEM_INIT_HEADER = {repr(static_header_bytes)}\n"
        
        # 5. Запись в целевой файл
        TARGET_FILE_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(TARGET_FILE_PATH, "w") as f_out:
            f_out.write("# WARNING: This file is automatically generated by create_init_constant.py\n")
            f_out.write("# It contains the static header block required for OEM INIT.SDL generation.\n")
            f_out.write(constant_value)

        print(f"✅ Успех! Статический заголовок извлечен ({len(static_header_bytes)} байт).")
        print(f"💾 Файл констант создан/обновлен: {TARGET_FILE_PATH}")
        print("\nТеперь вы можете запустить основной билд, используя эту константу.")

    except Exception as e:
        print(f"❌ Критическая ошибка при обработке: {e}")
        sys.exit(1)

if __name__ == "__main__":
    extract_and_create_constant()